// <auto-generated />
using System;
using MarcadorBaloncesto.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarcadorBaloncesto.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250820043333_CreatePartidosTable")]
    partial class CreatePartidosTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarcadorBaloncesto.API.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EquipoLocal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EquipoVisitante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FaltasLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FaltasVisitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("FechaPartido")
                        .HasColumnType("datetime2");

                    b.Property<int>("PuntosLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PuntosVisitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EquipoLocal");

                    b.HasIndex("EquipoVisitante");

                    b.ToTable("Partidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipoLocal = "Lakers",
                            EquipoVisitante = "Warriors",
                            FaltasLocal = 15,
                            FaltasVisitante = 12,
                            FechaPartido = new DateTime(2025, 8, 19, 22, 33, 33, 96, DateTimeKind.Local).AddTicks(5739),
                            PuntosLocal = 110,
                            PuntosVisitante = 105
                        },
                        new
                        {
                            Id = 2,
                            EquipoLocal = "Bulls",
                            EquipoVisitante = "Celtics",
                            FaltasLocal = 10,
                            FaltasVisitante = 8,
                            FechaPartido = new DateTime(2025, 8, 19, 22, 33, 33, 96, DateTimeKind.Local).AddTicks(5755),
                            PuntosLocal = 95,
                            PuntosVisitante = 98
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
